name: toki_principal
description: A school management Flutter application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons (Professional pack)
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.7.0
  flutter_slidable: ^3.0.0

  # UI & Charts
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1

  # Functionality
  image_picker: ^1.1.2
  intl: ^0.19.0

  # ✅ IMPORTANT: Homework worksheets aur files upload karne ke liye
  file_picker: ^8.1.7

  # ✅ IMPORTANT: Call, Email aur External URL open karne ke liye
  url_launcher: ^6.3.0
  flutter_riverpod: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets folder setup
  assets:
    - assets/images/